### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by cybercyb** [Haileykins/AutoBroadcasterPlus#4]
[AutoBroadcasterPlus] Task #897 for AutoBroadcasterPlus v1.3 generated an exception
java.lang.NullPointerException: null
	at me.haileykins.autobroadcasterplus.utils.Autobroadcaster.lambda$broadcast$0(Autobroadcaster.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Haileykins** [comment]
I will look into it tonight! Would you be able to give me more information regarding the server, plugins you use, server version, etc.

In the meantime please try to create a copy of your messages file and send it to me here, and let the plugin regenerate a brand new file, if something in the messages file is typed wrong the plugin won't be able to read the file right, therefore will throw an exception on broadcast attempts.

**Comment by Haileykins** [comment]
For reference please only create one issue.
GitHub was not notifying me of alerts for some reason, I will look into that, closing this in favor of the issue you create issue number 3
